### PR TITLE
Add multiplay mode support.

### PR DESCRIPTION
**Pull request by Crescent696**
Hi thojmr!

Thanks for supports.
I add some logic to inflate female character in multiplay mode, tested in HS2.
btw, I removed inflation trigger when finish out side, it would be more appropriate imo.

I'll implement some deflate logic in next few days.
Is it okay if I put config value into config GUI? that would be easier to toggle value.

### CODE REVIEW

**Comment by thojmr** [comment]
No problem!
The finish outside part was just used for deflation logic in AI_Pregnancy and I was just too lazy to remove it so that's fine.
If you want to add to the GUI config, go for it.

**Comment by thojmr** [comment]
If you have more changes, just add them to this pull request.  Ill just leave it open until you're ready.

**Comment by Crescent696** [comment]
Have been busy last week, I’ll push some new commit to night.

**Comment by Crescent696** [comment]
Hi thojmr!
Done deflate logic for HS2.
No new ideas for now.

**Comment by thojmr** [comment]
Thanks for this,  Ill put it thought a round of testing later tonight.

**Comment by thojmr** [comment]
Alright, the only issue Ive found is when "chaF_003" exists, no inflation happens, because the code is only looking for 01 and 02.  Seems that sometimes instead of chaF_001 and chaF_002, you can have chaF_002 and chaF_003, when in multi HScene. At least this is the case when I choose "Random" for the second heroine

Otherwise the rest looks good.  I went ahead and moved some of the hooks into a separate file for cleanliness.

**Pull request merged**
